[[news]]
date = "Reviewer"
content = """Neurips 2023-, ICLR 2024-, ICML 2024-, AAAI 2025-, AISTATS 2025"""

[[news]]
date = "Organizing Committee"
content = """[AI for Fully-Automated Chip Design (AI4FACD) Workshop](https://ai4facd.github.io/2024/) @ [ISCA 2024](https://iscaconf.org/isca2024/)"""